In [14]:
import pandas as pd

In [15]:
data = pd.read_csv('https://raw.githubusercontent.com/andreandriand/dataset/main/AirPassengers.csv')

In [16]:
p = data['#Passengers']

In [24]:
from numpy import array
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
  X, y = list(), list()
  for i in range(len(sequence)):
    # find the end of this pattern
    end_ix = i + n_steps
    # check if we are beyond the sequence
    if end_ix > len(sequence)-1:
      break
    # gather input and output parts of the pattern
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return array(X), array(y)

# define univariate time series
series = p
print(series.shape)
# transform to a supervised learning problem
X, y = split_sequence(series, 3)
print(X.shape, y.shape)
# show each sample
for i in range(len(X)):
  print(X[i], y[i])

(144,)
(141, 3) (141,)
[112 118 132] 129
[118 132 129] 121
[132 129 121] 135
[129 121 135] 148
[121 135 148] 148
[135 148 148] 136
[148 148 136] 119
[148 136 119] 104
[136 119 104] 118
[119 104 118] 115
[104 118 115] 126
[118 115 126] 141
[115 126 141] 135
[126 141 135] 125
[141 135 125] 149
[135 125 149] 170
[125 149 170] 170
[149 170 170] 158
[170 170 158] 133
[170 158 133] 114
[158 133 114] 140
[133 114 140] 145
[114 140 145] 150
[140 145 150] 178
[145 150 178] 163
[150 178 163] 172
[178 163 172] 178
[163 172 178] 199
[172 178 199] 199
[178 199 199] 184
[199 199 184] 162
[199 184 162] 146
[184 162 146] 166
[162 146 166] 171
[146 166 171] 180
[166 171 180] 193
[171 180 193] 181
[180 193 181] 183
[193 181 183] 218
[181 183 218] 230
[183 218 230] 242
[218 230 242] 209
[230 242 209] 191
[242 209 191] 172
[209 191 172] 194
[191 172 194] 196
[172 194 196] 196
[194 196 196] 236
[196 196 236] 235
[196 236 235] 229
[236 235 229] 243
[235 229 243] 264
[229 243 264] 272
[243 264 272] 237
[264 

In [23]:
# transform input from [samples, features] to [samples, timesteps, features]
# X = X.reshape((X.shape[0], X.shape[1], 1))
# print(X)

In [32]:
newX = pd.DataFrame(X, columns=['Xt-2', 'Xt-1', 'Xt'])
newY = pd.DataFrame(y, columns=['Output'])

In [34]:
newDf = pd.concat([newX,newY], axis=1)
newDf

Xt-2  Xt-1   Xt  Output
0     112   118  132     129
1     118   132  129     121
2     132   129  121     135
3     129   121  135     148
4     121   135  148     148
..    ...   ...  ...     ...
136   472   535  622     606
137   535   622  606     508
138   622   606  508     461
139   606   508  461     390
140   508   461  390     432

[141 rows x 4 columns]

In [36]:
csv = newDf.to_csv('timeseries.csv')